config/routes.rb
Rails.application.routes.draw do
  devise_for :users
	root to: "articles#index"

	get 'home/index'
	get 'contacts' => 'contacts#new'
	get 'terms' => 'pages#terms'
  get 'about' => 'pages#about'
  resource :contacts, only: [:new, :create],path_names: {:new => ''}
	# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
	resources :articles do 
		resources :comments
	end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
	validates :title, :text, presence: true
	has_many :comments

	attr_accessor :regenerate_permalink

	before_save :set_permalink

	def subject
		title
	end

	def last_comment
		comments.last
	end

	def generate_permalink(count=0)
		 new_permalink = title.parameterize[0..49]

		 if count > 0
			new_permalink += "-#{count}"
		 end

		 if Article.where.not(id: id).find_by(permalink: new_permalink)
			new_permalink = generate_permalink(count + 1)
		 end

		 new_permalink
	end

	def to_param
		permalink
	end

	private
	def set_permalink
		if regenerate_permalink.to_i > 0 || (new_record? && !permalink?)
			self.permalink = generate_permalink
		end
	end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
end

app/models/contact.rb
class Contact < ApplicationRecord
	validates :email, presence: true
	validates :message, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	before_action :authenticate_user!
	before_action :set_article, only: [:show, :edit, :update, :destroy]


	def index
		@articles = Article.all
	end

	def new
	end
	
	def update
		if @article.update(article_params)
			redirect_to @article
		else
			render :edit
		end
	end

	def edit
	end
	
	def show
	end
	
  def create
    @article = Article.new(article_params)
    if @article.valid?
      @article.save
      redirect_to @article
    else
      render action: 'new'
    end
	end
	
	def destroy
		@article.destroy
	
		redirect_to articles_path
	end

	private
	def set_article
		@article = Article.find_by!(permalink: params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :text, :regenerate_permalink)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	def create
    @article = Article.find(params[:article_id])
    @article.comments.create(comment_params)

    redirect_to article_path(@article)
  end

  private

  def comment_params
    params.require(:comment).permit(:author, :body)
  end

end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
	def new
	end
	def create
		@contact = Contact.new(contact_params)
		if @contact.valid?
			@contact.save
		else
			render action: 'new'
		end
	end

	private
	def contact_params
		params.require(:contact).permit(:email, :message)
	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def terms
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/edit.html.erb
<h1>Edit article</h1>

<%= form_for @article, method: :patch do |f| %>
<p>
  <%= f.label :title %>
  <%= f.text_field :title %>
</p>
<p>
  <%= f.label :text %>
  <%= f.text_area :text %>
</p>
	<% if f.object.persisted? %>
		<p>
			<%= f.check_box :regenerate_permalink %>
			<%= f.label :regenerate_permalink %>
		</p>
	<% end %>
<p>
  <%= f.submit %>
</p>

<% end %>

app/views/articles/index.html.erb
<% @articles.each do |article| %>
  <h3><%= article.title %></h3>
  <p><%= article.text %></p>
  <p><%= link_to  "Show article", article_path(article) %> | <%= link_to  "Edit article", edit_article_path(article) %> | <%= link_to "Destroy", article_path(article), method: :delete, data: { confirm: 'Действительно удалить?'} %></p>
  <hr>
<% end %>

app/views/articles/new.html.erb
<h1>Article</h1>
<%= form_for :article,url: articles_path do |f| %>
	<p>
		<%= f.label :title %>
		<%= f.text_field :title %>
	</p>
	<p>
		<%= f.label :text %>
		<%= f.text_area :text %>
	</p>
	<p>
		<%= f.submit %>
	</p>
<% end %>

app/views/articles/show.html.erb
<h1><%= @article.title %></h1>

<p><%= @article.text %></p>
<h2>Comments</h2>
<% @article.comments.each do |comment| %>
	<p>
		<i><%= comment.author %> said:</i><br>
		<%= comment.body %>
	</p>
<% end %>
<h2>Add Comment</h2>
<p>
<%= form_for([@article, @article.comments.build]) do |f| %>

  <p>
    <%= f.label :author %>
    <%= f.text_field :author %>
  </p>
  <p>
    <%= f.label :body %>
    <%= f.text_area :body %>
  </p>

  <p><%= f.submit %></p>


<% end %>
</p>

app/views/contacts/create.html.erb
<p>Thanks!</p>

app/views/contacts/new.html.erb
<h1><%= t('contacts.contact_us') %></h1>

<%= form_for :contact,url: contacts_path do |f| %>
	<% if @contact && @contact.errors.any? %>
	<p>
			<ul>
		<%= @contact.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>
		<% end %>
			</ul>
	</p>
	<% end %>
	<p>
		<%= f.label :email %>
		<%= f.text_field :email %>
	</p>
	<p>
		<%= f.label :message %>
		<%= f.text_area :message %>
	</p>
	<p>
		<%= f.submit "Send message" %>
	</p>
<% end %>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
		<p class="notice"><%= notice %></p>
  	<p class="alert"><%= alert %></p>
		<% if user_signed_in? %> <%= current_user.email %> | <a href="/users/sign_out" data-method="delete">Sign Out</a></p>
		<% else %>
			<p><a href="/users/sign_in">Sign In</a> 
		<% end %>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h2>О нас</h2>

app/views/pages/terms.html.erb
<h1>Правила</h1>